HOUSE PRICE PREDICTION (DELHI)

In [ ]:
import pandas as pd
import numpy as np

Data Pre Proccessing

In [ ]:
import kagglehub
path = kagglehub.dataset_download("goelyash/housing-price-dataset-of-delhiindia")

Downloading to /root/.cache/kagglehub/datasets/goelyash/housing-price-dataset-of-delhiindia/3.archive...

100%|██████████| 944k/944k [00:00<00:00, 108MB/s]

Extracting files...

In [ ]:
import os
os.listdir(path)

['Delhi_v2.csv']

In [ ]:
data = pd.read_csv(path + '/Delhi_v2.csv')
data.head()

   Unnamed: 0  ...   Price_sqft
0           0  ...  4148.148148
1           1  ...  5906.040268
2           2  ...  6918.238994
3           3  ...  3628.571429
4           4  ...  4592.592593

[5 rows x 18 columns]

In [ ]:
data.shape

(7738, 18)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        7738 non-null   int64
 1   price             7738 non-null   float64
 2   Address           7738 non-null   object
 3   area              7738 non-null   float64
 4   latitude          7738 non-null   float64
 5   longitude         7738 non-null   float64
 6   Bedrooms          7738 non-null   float64
 7   Bathrooms         7738 non-null   float64
 8   Balcony           5166 non-null   float64
 9   Status            7164 non-null   object
 10  neworold          7738 non-null   object
 11  parking           2612 non-null   float64
 12  Furnished_status  4124 non-null   object
 13  Lift              1733 non-null   float64
 14  Landmarks         2759 non-null   object
 15  type_of_building  7738 non-null   object
 16  desc              7738 non-null   object
 17  Price_sqft        7738 non-null   float64
dtypes: float64(10), int64(1), object(7)
memory usage: 1.1+ MB

In [ ]:
for column in data.columns :
  print(data[column].value_counts())
  print("*" * 20)

Unnamed: 0
7737    1
0       1
1       1
2       1
3       1
       ..
14      1
13      1
12      1
11      1
10      1
Name: count, Length: 7738, dtype: int64
********************
price
4500000.0     290
3500000.0     252
4000000.0     247
6000000.0     243
5500000.0     223
             ...
2480000.0       1
19800000.0      1
5140000.0       1
47000000.0      1
8450000.0       1
Name: count, Length: 584, dtype: int64
********************
Address
Raj Nagar Extension, Ghaziabad, Delhi NCR                                     163
Indirapuram, Ghaziabad, Delhi NCR                                             152
Greater Noida West, Greater Noida, Delhi NCR                                  100
Noida Extension, Noida, Delhi NCR                                              63
Crossings Republik, Ghaziabad, Delhi NCR                                       61
                                                                             ...
Ramakrishna apartment, Indraprastha Extension, New Delhi - East, Delhi NCR      1
Rajnagar Extension Gahziabad, Raj Nagar Extension, Ghaziabad, Delhi NCR         1
Rajendra Park, Rajendra Park, Gurgaon, Delhi NCR                                1
704/4 Vipul Lavanya, Sector 81, Gurgaon, Delhi NCR                              1
101 first floor Gate 10, Shalimar Garden Extension 1, Ghaziabad, Delhi NCR      1
Name: count, Length: 4145, dtype: int64
********************
area
900.0     325
1000.0    264
1100.0    205
1200.0    156
800.0     137
         ...
565.0       1
629.0       1
1514.0      1
2445.0      1
853.0       1
Name: count, Length: 1102, dtype: int64
********************
latitude
28.605958    101
28.649348     79
28.704053     62
28.646286     37
28.664488     30
            ...
28.636213      1
28.462559      1
28.526541      1
28.619899      1
28.677111      1
Name: count, Length: 2942, dtype: int64
********************
longitude
77.444512    101
77.369626     79
77.437331     62
77.406051     37
77.347494     30
            ...
77.316510      1
77.342293      1
77.107018      1
77.025955      1
77.095581      1
Name: count, Length: 2912, dtype: int64
********************
Bedrooms
2.0     3525
3.0     3373
4.0      642
5.0       98
6.0       46
7.0       17
9.0       16
10.0      11
8.0       10
Name: count, dtype: int64
********************
Bathrooms
2.0     5051
3.0     1907
4.0      551
5.0      138
6.0       44
7.0       21
8.0       12
9.0       10
10.0       4
Name: count, dtype: int64
********************
Balcony
2.0     1793
3.0     1516
1.0     1082
4.0      613
5.0      130
6.0       21
7.0        4
10.0       3
8.0        3
9.0        1
Name: count, dtype: int64
********************
Status
Ready to Move         7148
Under Construction      16
Name: count, dtype: int64
********************
neworold
Resale          6905
New Property     833
Name: count, dtype: int64
********************
parking
1.0      1715
2.0       640
3.0       110
4.0        45
6.0        14
         ...
20.0        1
145.0       1
99.0        1
303.0       1
179.0       1
Name: count, Length: 65, dtype: int64
********************
Furnished_status
Semi-Furnished    2199
Unfurnished       1230
Furnished          695
Name: count, dtype: int64
********************
Lift
2.0     800
1.0     296
0.0     269
3.0     258
4.0      86
6.0       8
5.0       7
7.0       4
10.0      2
8.0       2
9.0       1
Name: count, dtype: int64
********************
Landmarks
metro station                                    8
NH 8 and Dwarka Expressway                       6
Shipra Mall                                      6
DPS School                                       6
VVIP Adress                                      5
                                                ..
Next to sector 78 metro station                  1
Main Market is just 100 mtr walking distance.    1
telephone exchange sector 12, gurgaon            1
Nearby Sanjay Park                               1
Near Sahibabad Railway station                   1
Name: count, Length: 2612, dtype: int64
********************
type_of_building
Flat                6226
Individual House    1512
Name: count, dtype: int64
********************
desc
\n                                                                                                                                                                                                                                                                                                                               3257
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                  145
\n                    \n                    \n                    \n                       property is in a good locality\n                    \n                                                                                                                                                                                  25
\n                    \n                    \n                    \n                       Builder floor apartment is available for sale. It is a good location property. Please contact for more details.\n                    \n                                                                                                 21
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale.it is a good location property. Please contact for more details.\n                    \n                                                                                                    20
                                                                                                                                                                                                                                                                                                                                 ...
\n                    \n                    \n                    \n                       0 km from West Vinod Nagar Metro StationDTC bust stop 0 Km\n                    \n                                                                                                                                                       1
\n                    \n                    \n                    \n                       Good Property location Good Area Family locationGood aminities\n                    \n                                                                                                                                                   1
\n                    \n                    \n                    \n                       Multistorey apartment is available for sale. It covered area of 1850 sq-ft, it is a good location property. Please contact for moreDetails\n                    \n                                                                       1
\n                    \n                    \n                    \n                       Recently renovated 3BHK on the ground floor. Inside a gated complex and at walking distance from the Vaishali Metro Station. Basement parking and a verandah at the rear.\n                    \n                                        1
\n                    \n                    \n                    \n                       Migsun green mansion zeta 1 greater noida900 spf semi furnished Wardrobes, moduler kichen, exhaust fan, all lights, png installed, one coverd car parking, all cartain, almunium word done\n                    \n                       1
Name: count, Length: 4181, dtype: int64
********************
Price_sqft
5000.000000     125
4000.000000      83
5555.555556      53
3333.333333      52
10000.000000     52
               ...
5062.500000       1
3942.307692       1
3606.557377       1
6220.095694       1
7683.215130       1
Name: count, Length: 3946, dtype: int64
********************

In [ ]:
data.isna().sum()

Unnamed: 0             0
price                  0
Address                0
area                   0
latitude               0
longitude              0
Bedrooms               0
Bathrooms              0
Balcony             2572
Status               574
neworold               0
parking             5126
Furnished_status    3614
Lift                6005
Landmarks           4979
type_of_building       0
desc                   0
Price_sqft             0
dtype: int64

In [ ]:
data.drop(columns = ['Unnamed: 0', 'Address','Lift', 'Landmarks', 'desc', 'Price_sqft'],inplace = True)

In [ ]:
data.describe()

              price         area  ...      Balcony      parking
count  7.738000e+03  7738.000000  ...  5166.000000  2612.000000
mean   8.320635e+06  1409.506591  ...     2.426442     7.673047
std    7.223197e+06   718.929581  ...     1.083677    60.417508
min    1.700000e+06   501.000000  ...     1.000000     1.000000
25%    4.200000e+06   990.000000  ...     2.000000     1.000000
50%    6.000000e+06  1250.000000  ...     2.000000     1.000000
75%    9.500000e+06  1650.000000  ...     3.000000     2.000000
max    8.500000e+07  9500.000000  ...    10.000000  1406.000000

[8 rows x 8 columns]

Filling missing Values

In [ ]:
data['Balcony'].value_counts()

Balcony
2.0     1793
3.0     1516
1.0     1082
4.0      613
5.0      130
6.0       21
7.0        4
10.0       3
8.0        3
9.0        1
Name: count, dtype: int64

In [ ]:
data['Balcony'] = data['Balcony'].apply(lambda x: 5 if pd.notnull(x) and x > 5 else x)

In [ ]:
data['Balcony'].value_counts()

Balcony
2.0    1793
3.0    1516
1.0    1082
4.0     613
5.0     162
Name: count, dtype: int64

In [ ]:
data['has_balcony'] = data['Balcony'].notnull().astype(int)
data['Balcony'] = data['Balcony'].fillna(data['Balcony'].median())

In [ ]:
data['Status'] = data['Status'].fillna('Unknown')

In [ ]:
data['Status'].value_counts()

Status
Ready to Move         7148
Unknown                574
Under Construction      16
Name: count, dtype: int64

In [ ]:
data['parking'].value_counts()

parking
1.0      1715
2.0       640
3.0       110
4.0        45
6.0        14
         ...
20.0        1
145.0       1
99.0        1
303.0       1
179.0       1
Name: count, Length: 65, dtype: int64

In [ ]:
data['parking'] = data['parking'].apply(lambda x: np.nan if x > 5 else x)
data['has_parking']=data['parking'].notnull().astype(int)
data['parking'] = data['parking'].fillna(0)

In [ ]:
data['has_parking'].value_counts()

has_parking
0    5216
1    2522
Name: count, dtype: int64

In [ ]:
data['Furnished_status']=data['Furnished_status'].fillna('Unkown')

In [ ]:
data['Furnished_status'].value_counts()

Furnished_status
Unkown            3614
Semi-Furnished    2199
Unfurnished       1230
Furnished          695
Name: count, dtype: int64

In [ ]:
data.isna().sum()

price               0
area                0
latitude            0
longitude           0
Bedrooms            0
Bathrooms           0
Balcony             0
Status              0
neworold            0
parking             0
Furnished_status    0
type_of_building    0
has_balcony         0
has_parking         0
dtype: int64

Removing outliers on the basis of area per room

In [ ]:
(data['area']/data['Bedrooms']).describe()

count    7738.000000
mean      515.630662
std       147.378756
min        50.700000
25%       425.000000
50%       500.000000
75%       590.000000
max      1900.000000
dtype: float64

In [ ]:
data = data[((data['area']/data['Bedrooms']) >= 300)]
data.describe()

              price         area  ...  has_balcony  has_parking
count  7.451000e+03  7451.000000  ...  7451.000000  7451.000000
mean   8.444595e+06  1434.195410  ...     0.667159     0.331365
std    7.303485e+06   719.381041  ...     0.471262     0.470736
min    1.700000e+06   600.000000  ...     0.000000     0.000000
25%    4.200000e+06  1000.000000  ...     0.000000     0.000000
50%    6.000000e+06  1265.000000  ...     1.000000     0.000000
75%    9.700000e+06  1660.000000  ...     1.000000     1.000000
max    8.500000e+07  9500.000000  ...     1.000000     1.000000

[8 rows x 10 columns]

Removing Price per square feet outliers by grouping latitude, longitude and bedrooms.

In [ ]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, random_state=0)
data['location_cluster'] = kmeans.fit_predict(data[['latitude', 'longitude']])  #Clustering latitudes and longitudes. This cluster resembles locality.

/tmp/ipykernel_2303/1848702.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['location_cluster'] = kmeans.fit_predict(data[['latitude', 'longitude']])  #Clustering latitudes and longitudes. This cluster resembles locality.

In [ ]:
data['price_per_sqft'] = data['price'] / data['area']
data['price_per_sqft'].describe()

/tmp/ipykernel_2303/1387902484.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['price_per_sqft'] = data['price'] / data['area']

count     7451.000000
mean      5498.470996
std       2259.931840
min       2100.000000
25%       3923.260950
50%       4948.453608
75%       6321.784150
max      25925.925926
Name: price_per_sqft, dtype: float64

In [ ]:
def remove_outliers(df):
  df_out = pd. DataFrame()
  for(cluster, bedroom), subdf in df.groupby(['location_cluster', 'Bedrooms']):
    m = subdf['price_per_sqft'].mean()
    s = subdf['price_per_sqft'].mean()
    reduced_df = subdf[(subdf['price_per_sqft'] > (m-s))  & (subdf['price_per_sqft'] > (m-s))]

    df_out = pd.concat([df_out, reduced_df], ignore_index=True)
  return (df_out)
data = remove_outliers(data)

In [ ]:
data.describe()

              price         area  ...  location_cluster  price_per_sqft
count  7.451000e+03  7451.000000  ...       7451.000000     7451.000000
mean   8.444595e+06  1434.195410  ...          3.541001     5498.470996
std    7.303485e+06   719.381041  ...          3.028771     2259.931840
min    1.700000e+06   600.000000  ...          0.000000     2100.000000
25%    4.200000e+06  1000.000000  ...          1.000000     3923.260950
50%    6.000000e+06  1265.000000  ...          2.000000     4948.453608
75%    9.700000e+06  1660.000000  ...          6.000000     6321.784150
max    8.500000e+07  9500.000000  ...          9.000000    25925.925926

[8 rows x 12 columns]

In [ ]:
data.drop(columns = ['price_per_sqft'], inplace = True)

In [ ]:
data.head()

        price    area   latitude  ...  has_balcony  has_parking  location_cluster
0   7700000.0  1250.0  28.436305  ...            1            0                 0
1   9000000.0  1481.0  28.497450  ...            1            1                 0
2  10500000.0  1020.0  28.397856  ...            1            0                 0
3   7500000.0  1505.0  28.512136  ...            1            1                 0
4   5600000.0   929.0  28.436305  ...            1            0                 0

[5 rows x 15 columns]

Model Building

In [ ]:
X = data.drop(columns = ['price'])
y = data['price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
Column_trans = make_column_transformer(
    (OneHotEncoder(sparse_output=False), ['Status', 'neworold', 'Furnished_status', 'type_of_building' ]),
    remainder='passthrough'
)
scaler = StandardScaler()
lr = LinearRegression()
pipe = make_pipeline(Column_trans, scaler, lr)

In [ ]:
pipe.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['Status', 'neworold',
                                                   'Furnished_status',
                                                   'type_of_building'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
Column_trans.get_feature_names_out()

array(['onehotencoder__Status_Ready to Move',
       'onehotencoder__Status_Under Construction',
       'onehotencoder__Status_Unknown',
       'onehotencoder__neworold_New Property',
       'onehotencoder__neworold_Resale',
       'onehotencoder__Furnished_status_Furnished',
       'onehotencoder__Furnished_status_Semi-Furnished',
       'onehotencoder__Furnished_status_Unfurnished',
       'onehotencoder__Furnished_status_Unkown',
       'onehotencoder__type_of_building_Flat',
       'onehotencoder__type_of_building_Individual House',
       'remainder__area', 'remainder__latitude', 'remainder__longitude',
       'remainder__Bedrooms', 'remainder__Bathrooms',
       'remainder__Balcony', 'remainder__parking',
       'remainder__has_balcony', 'remainder__has_parking',
       'remainder__location_cluster'], dtype=object)

In [ ]:
y_pred_lr = pipe.predict(X_test)

In [ ]:
r2_score(y_test, y_pred_lr)

0.7875060558004727

Applying Lasso

In [ ]:
lasso = Lasso()
pipe = make_pipeline(Column_trans, scaler, lasso)
pipe.fit(X_train, y_train)
y_pred_lasso = pipe.predict(X_test)

In [ ]:
r2_score(y_test, y_pred_lasso)

0.7875060057801819

Applying Ridge

In [ ]:
ridge = Ridge()
pipe = make_pipeline(Column_trans, scaler, ridge)
pipe.fit(X_train, y_train)
y_pred_ridge = pipe.predict(X_test)

In [ ]:
r2_score(y_test, y_pred_ridge)

0.7874789234671475

Random Forest Regressor

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rand_forest = RandomForestRegressor()
pipe = make_pipeline(Column_trans, scaler, rand_forest)
pipe.fit(X_train, y_train)
y_pred_rand_forest = pipe.predict(X_test)

In [ ]:
r2_score(y_test, y_pred_rand_forest)

0.9364109715599132

In [ ]:
train_score = pipe.score(X_train, y_train)
test_score = pipe.score(X_test, y_test)

print(train_score, test_score)

0.9884599308781791 0.9364109715599132

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(pipe, X, y, cv=5)
print(scores.mean())

0.7327031041306146